workflows:
  default:
    name: Build and Upload
    max_build_duration: 90
    scripts:
      - name: Install dependencies
        script: |
          sudo apt update
          sudo apt install -y aria2
          mkdir -p downloads

      - name: Download torrents
        script: |
          echo "Starting torrent download..."
          aria2c --seed-time=0 --dir=downloads --select-file=1-16 "magnet:?xt=urn:btih:4BB0CE70EF23EB6D9F126D493DBBF01EA98A7B6F&dn=Tiny+Toon+Adventures+1990+S01+1080p+DVD+UPSCALED+DD+5.1+x265-edge...%20%20%20%20%20%20%20%20&tr=udp://tracker.bittor.pw:1337/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.opentrackr.org:1337/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.dler.org:6969/announce%20%20%20%20%20%20%20%20&tr=udp://open.stealth.si:80/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.torrent.eu.org:451/announce%20%20%20%20%20%20%20%20&tr=udp://exodus.desync.com:6969/announce%20%20%20%20%20%20%20%20&tr=udp://open.demonii.com:1337/announce"
          echo "Uploading files to Pixeldrain..."

          find downloads -type f | while read file; do
            echo "Uploading $file..."
            curl --globoff -T "$file" -u :92d49f17-2927-4f30-909d-c6ca8157bbed https://pixeldrain.com/api/file/
          done
