workflows:
  default:
    name: Build and Upload
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm curl
          npm install -g webtorrent-cli
          mkdir -p downloads

      - name: Download torrents
        script: |
          echo "Starting torrent download..."
          npx webtorrent download "magnet:?xt=urn:btih:0D92BDD53B367053A37E8741E50D8183405159CC&dn=Shaun+the+Sheep+%282007%29+Season+1-5+S01-S05+%2B+Specials+%281080p+BluRay+x265+HEVC+10bit+Mixed+5.1+Ghost%29+%5BQxR%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce" --out downloads
          echo "Uploading files to Pixeldrain..."

          find downloads -type f | while read file; do
            echo "Uploading $file..."
            curl --globoff -T "$file" -u :92d49f17-2927-4f30-909d-c6ca8157bbed https://pixeldrain.com/api/file/
          done
