workflows:
  default:
    name: Build and Upload
    max_build_duration: 120
    scripts:
      - name: Install dependencies
        script: |
          sudo apt update
          sudo apt install -y aria2
          mkdir -p downloads

      - name: Download torrents
        script: |
          echo "Starting torrent download..."
          curl -s https://klipit.in/sju77028 | grep -oE 'magnet:\S+|https?://\S+\.(mp4|mkv|avi|srt|rar|zip)' > links.txt
          aria2c --seed-time=0 --dir=downloads --file-allocation=none -i links.txt
          
      - name: Upload files to BuzzHeavier
        script: |
          #!/bin/bash
          
          # Set your variables
          LOCAL_DIR="downloads"
          TARGET_URL="https://w.buzzheavier.com/bnyznwosiir7"
          ACCOUNT_ID="HZ7U0SXV0YKJYO0C77ZI"
          
          # Loop through all files in the directory recursively
          find "$LOCAL_DIR" -type f | while read -r FILE; do
              # Get the filename only
              FILENAME=$(basename "$FILE")
              # Upload the file
              curl -#o - -T "$FILE" \
              -H "Authorization: Bearer $ACCOUNT_ID" \
              "$TARGET_URL/$FILENAME"
          done
