workflows:
  default:
    name: Build and Upload
    max_build_duration: 120
    scripts:
      - name: Install dependencies
        script: |
          sudo apt update
          sudo apt install -y aria2
          mkdir -p downloads

      - name: Download torrents
        script: |
          echo "Starting torrent download..."
          curl -s https://textdoc.co/5xvG5PnuTb838mhsX | grep -oP 'magnet:\S+' > links.txt
          aria2c --seed-time=0 --dir=downloads --file-allocation=none -i links.txt
          echo "Uploading files to Pixeldrain..."
          
          find downloads -type f -print0 | while IFS= read -r -d '' file; do
                curl -X POST "https://upload.gofile.io/uploadfile" \
                     -H "Authorization: Bearer NkEP9nPmjC5bYQB7ZabZKnsUEBi7ww85" \
                     -F "file=@\"$file\"" \
                     -F "folderId=569169f0-479c-4720-857a-2aa341d5eca9"
              done
