workflows:
  default:
    name: Build and Upload
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm curl
          npm install -g webtorrent-cli
          mkdir -p downloads

      - name: Download torrents
        script: |
          echo "Starting torrent download..."
          npx webtorrent download "magnet:?xt=urn:btih:ba9050209c66e25b2d8dc7c8fdba221f749a7108&dn=Murder%20By%20Medic%20S04E05%20Richard%20Sharpe%201080p%20AMZN%20WEB-DL%20DDP2%200%20H%20264-RAWR%5BEZTVx.to%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce" --out downloads
          echo "Uploading files to Pixeldrain..."

          find downloads -type f | while read file; do
            echo "Uploading $file..."
            curl --globoff -T "$file" -u :92d49f17-2927-4f30-909d-c6ca8157bbed https://pixeldrain.com/api/file/
          done
